# Temporarily Static Objects
TSO:
  # чтобы фильтровать совсем уж маленькие фрагменты
  AREA_THRESH_FRAME_PERCENT: 0.01
  # 4 или 8 пикселей задействовать для связных областей
  CON_COMPONENTS_CONNECTIVITY: 8

# Модель вычитания фона
BG_SUBTRACTION:
  # Настройки GSOC-модели
  GSOC_MODELS:
    # сколько положительных результатов должен получить образец,
    # прежде чем он будет рассматриваться в качестве возможной замены.
    HITS_THRESHOLD: 8192
    # как быстро будет обновляться быстрая
    REPLACE_RATE_FAST: 0.003
    # и медленная модели
    REPLACE_RATE_SLOW: 0.0003
  # параметры для морфологического закрытия
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 5
      - 5
    ITERATIONS: 2
  # во сколько раз уменьшать изображение прежде чем применять модель
  # (для лучшей производительности на больших изображениях)
  REDUCE_FRAME_SHAPE_MULTIPLIER: 3

# Unattended Objects Detector
UOD:
  # параметры YOLO-детектора
  HUMAN_DETECTION:
    YOLO_MODEL: "n"
    YOLO_CONFIDENCE: 0.25
  # граница для сопоставления объектов между кадров по IOU
  IOU_THRESHOLD: 0.2
  # на сколько должна увеличиться площадь контура объекта, чтобы
  # изменить координаты рамки, в %
  DETECTED_OBJ_AREA_THRESHOLD: 2
  # через сколько кадров обнаруженный становится подозрительным
  DETECTED_TO_SUSPICIOUS_TIMEOUT: 300
  # через сколько кадров подозрительный становится унесенным
  SUSPICIOUS_TO_UNATTENDED_TIMEOUT: 150

DETECTED_OBJECT:
  # ВРЕМЕННОЕ РЕШЕНИЕ
  # количество кадров, прошедшее с момента фактического появления
  # в кадре до момента появления в маске
  DEFAULT_OBSERVATION_COUNTER: 50
  # количество кадров, которое должно пройти, чтобы забыть объект
  DEFAULT_DISAPPEARANCE_COUNTER: 60
