BG_SUBTRACTION:
  GSOC_MODELS:
    HITS_THRESHOLD: 4096
    REPLACE_RATE_FAST: 0.002
    REPLACE_RATE_SLOW: 0.0002
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 5
      - 5
    ITERATIONS: 2
  REDUCE_FRAME_SHAPE_MULTIPLIER: 3
  CON_COMPONENTS_CONNECTIVITY: 4

UOD:
  HUMAN_DETECTION:
    YOLO_MODEL: "n"
    YOLO_CONFIDENCE: 0.25
  AREA_THRESH_FRAME_PERCENT: 1.5
