BG_SUBTRACTION:
  GSOC_MODELS:
    HITS_THRESHOLD: 4096
    REPLACE_RATE_FAST: 0.002
    REPLACE_RATE_SLOW: 0.0002
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 3
      - 3
    ITERATIONS: 2
  REDUCE_FRAME_SHAPE_MULTIPLIER: 3

HUMAN_DETECTION:
  YOLO_MODEL: "n"
  YOLO_CONFIDENCE: 0.25
