# Temporarily Static Objects
TSO:
  # чтобы фильтровать совсем уж маленькие фрагменты
  AREA_THRESH_FRAME_PERCENT: 0.01
  # 4 или 8 пикселей задействовать для связных областей
  CON_COMPONENTS_CONNECTIVITY: 8

# Модель вычитания фона
BG_SUBTRACTION:
  # Настройки GSOC-модели
  GSOC_MODELS:
    # сколько положительных результатов должен получить образец,
    # прежде чем он будет рассматриваться в качестве возможной замены.
    HITS_THRESHOLD: 4096
    # как быстро будет обновляться быстрая
    REPLACE_RATE_FAST: 0.003
    # и медленная модели
    REPLACE_RATE_SLOW: 0.00003
  # параметры для морфологического закрытия
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 5
      - 5
    ITERATIONS: 2
  # во сколько раз уменьшать изображение прежде чем применять модель
  # (для лучшей производительности на больших изображениях)
  REDUCE_FRAME_SHAPE_MULTIPLIER:
    LONG_RANGE: 1  # для дальнего плана
    SEMI_LONG_RANGE: 2  # для среднего плана
    CLOSE_RANGE: 4  # для ближнего плана

# Unattended Objects Detector
UOD:
  # параметры YOLO-детектора
  HUMAN_DETECTION:
    YOLO_MODEL: "n"
    YOLO_CONFIDENCE: 0.25
  # граница для сопоставления объектов между кадров по IOU
  IOU_THRESHOLD: 0.2
  # на сколько должна измениться площадь контура объекта, чтобы
  # изменить координаты рамки, в %
  DETECTED_OBJ_AREA_THRESHOLD: 2
  # через сколько секунд обнаруженный становится подозрительным
  DETECTED_TO_SUSPICIOUS_TIMEOUT: 25
  # через сколько секунд подозрительный становится унесенным
  SUSPICIOUS_TO_UNATTENDED_TIMEOUT: 10
  # через сколько секунд не нахождения в маске предмет теряется
  DISAPPEARANCE_TIMEOUT: 6
  # сколько секунд истории хранить
  HISTORY_ACCUMULATION_TIME: 15
  # сколько кадров сохранить
  FRAMES_TO_SAVE_NUMBER: 15
