BG_SUBTRACTION:
  GSOC_MODELS:
    HITS_THRESHOLD: 8192
    REPLACE_RATE_FAST: 0.003
    REPLACE_RATE_SLOW: 0.0003
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 5
      - 5
    ITERATIONS: 2
  REDUCE_FRAME_SHAPE_MULTIPLIER: 3

UOD:
  HUMAN_DETECTION:
    YOLO_MODEL: "n"
    YOLO_CONFIDENCE: 0.25
  CON_COMPONENTS_CONNECTIVITY: 8
  # чтобы фильтровать совсем уж маленькие фрагменты
  AREA_THRESH_FRAME_PERCENT: 0.1
  # граница для сопоставления объектов между кадров по IOU
  IOU_THRESHOLD: 0.2
  # на сколько должна увеличиться площадь контура объекта, чтобы
  # изменить координаты рамки
  DETECTED_OBJ_AREA_THRESHOLD: 0.2
  # через сколько кадров обнаруженный становится подозрительным
  DETECTED_TO_SUSPICIOUS_TIMEOUT: 150
  # через сколько кадров подозрительный становится унесенным
  SUSPICIOUS_TO_UNATTENDED_TIMEOUT: 300

DETECTED_OBJECT:
  # ВРЕМЕННОЕ РЕШЕНИЕ
  # количество кадров, прошедшее с момента фактического появления
  # в кадре до момента появления в маске
  DEFAULT_OBSERVATION_COUNTER: 570
  # количество кадров, которое должно пройти, чтобы забыть объект
  DEFAULT_DISAPPEARANCE_COUNTER: 60
